# Generated by Django 5.2.4 on 2025-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_false', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tf_question',
            options={'verbose_name': 'True/False Question', 'verbose_name_plural': 'True/False Questions'},
        ),
        migrations.AlterField(
            model_name='tf_question',
            name='correct',
            field=models.BooleanField(default=False, help_text='Is the answer True or False', verbose_name='Correct'),
        ),
    ]
